version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bankcards-db
    environment:
      POSTGRES_DB: Bank_REST
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sss3365007
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge
